CheckLinks: false # don't check URLs in <link> elements
IgnoreDirectoryMissingTrailingSlash: true # don't fail when directory links don't have a trailing slash - techdocs generates a lot of valid links that would cause this check to fail
IgnoreHTTPStatusCodes: [429] # suppress failures of URLs containing 429
IgnoreURLs:
  - "localhost" # suppress failures of URLs containing localhost
  - "https://github.com/bcgov-c"
  - "https://loginproxy.gov.bc.ca"
  - "https://login.nimbus.cloud.gov.bc.ca/"
  - "https://techcommunity.microsoft.com/blog/" # Although this is a valid URL, the link validation times out
  - "https://github.com/Azure/azqr/blob/main/examples/cicd/github-actions.yml" # Although this is a valid link, the link validation fails
  - "https://github.com/Azure/azqr/blob/main/examples/cicd/azdo-pipeline.yml" # Although this is a valid link, the link validation fails
