CheckLinks: false # don't check URLs in <link> elements
IgnoreDirectoryMissingTrailingSlash: true # don't fail when directory links don't have a trailing slash - techdocs generates a lot of valid links that would cause this check to fail
IgnoreURLs:
    - "localhost" # suppress failures of URLs containing localhost
    - "https://github.com/bcgov-c"
    - "https://loginproxy.gov.bc.ca"
    - "https://login.nimbus.cloud.gov.bc.ca/"
    - "https://techcommunity.microsoft.com/blog/finopsblog/how-to-budget-your-azure-cloud-spend-with-microsoft-cost-management/4153963" # Although this is a valid URL, the link validation times out
