CheckLinks: false # don't check URLs in <link> elements
IgnoreDirectoryMissingTrailingSlash: true # don't fail when directory links don't have a trailing slash - techdocs generates a lot of valid links that would cause this check to fail
IgnoreURLs:
  - "localhost" # suppress failures of URLs containing localhost
  - "https://github.com/bcgov-c"
  - "https://github.com/bcgov/public-cloud-techdocs/edit/" # ignore GitHub edit URLs that get rate limited (429 errors)
  - "https://loginproxy.gov.bc.ca"
  - "https://login.nimbus.cloud.gov.bc.ca/"
  - "https://ssbc-client.gov.bc.ca/"
  - "https://digital.gov.bc.ca/"
