name: TechDocs Pull Request Checks

on:
    workflow_dispatch:
    pull_request:

jobs:
    techdocs_pr_job:
        runs-on: ubuntu-latest

        name: Build and Check TechDocs
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            
            -   uses: tj-actions/changed-files@v45
                name: Check for changed files
                id: changed-files
                with:
                    files: '**/*.md'
                    separator: ","
            
            -   uses: DavidAnson/markdownlint-cli2-action@v18
                name: Lint Markdown files
                if: steps.changed-files.outputs.any_changed == 'true'
                with:
                    globs: ${{ steps.changed-files.outputs.all_changed_files }}
                    separator: ","

            -   name: Build TechDocs
                uses: bcgov/devhub-techdocs-publish@stable
                id: build_only
                with:
                    strict_validation: 'true'
                    publish: 'false'
                    production: 'false'
                    bucket_name: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
                    s3_access_key_id: ${{ secrets.TECHDOCS_AWS_ACCESS_KEY_ID }}
                    s3_secret_access_key: ${{ secrets.TECHDOCS_AWS_SECRET_ACCESS_KEY }}
                    s3_region: ${{ secrets.TECHDOCS_AWS_REGION }}
                    s3_endpoint: ${{ secrets.TECHDOCS_AWS_ENDPOINT }}
